[package]
name = "hw2"
version = "0.1.0"
authors = ["saadhika <saadhika@adobe.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
array2d = "*"
