matrix:
  include:
    - language: scala
      scala:
        - 2.11.7
      jdk:
        - openjdk8
      before_install:
        - cd Scala
#
#    - language: lua
#      lua:
#        - 5.2.3
#      install:
#        -
#      script:
#        - echo "ToDo"
#      before_install:
#        - cd Lua
#        - echo "Testing"
#      after_success:
#        - echo "Test Success"

    - language: rust
      rust:
        - 1.45.2
      before_install:
        - cd Rust
        - cd hw2
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all

notifications:
  email:
    - ppenmet@ncsu.edu
    - sadhika2@ncsu.edu
    - sray9@ncsu.edu
    - nshukla2@ncsu.edu
