matrix:
  include:
    - language: scala
      scala:
        - 2.9.3
      jdk:
        - openjdk8
    - language: lua
      lua:
        - 5.2.3
    - language: rust
      rust:
        - 2.6

notifications:
  email:
    - ppenmet@ncsu.edu
    - sadhika2@ncsu.edu
    - sray9@ncsu.edu
    - nshukla2@ncsu.edu

install:
  -
  
script:
  - echo "ToDO"

before_install:
  - echo "Testing"
  
after_success:
  - echo "Test Success"